# domains/ml - Python ML
genrule(
    name = "ml_python",
    out = "train.py",
    srcs = ["python/train.py"],
    cmd = "repo=\\$(git rev-parse --show-toplevel); cp \"$repo/domains/ml/python/train.py\" \"$OUT\"",
)
