load("//build_defs:ts_project.bzl", "ts_project")

ts_project(
    name = "monorepo-tooling",
    package_dir = "libs/monorepo-tooling",
    srcs = glob([
        "src/*.ts",
        "test/*.ts",
        "scripts/*.sh",
        "package.json",
        "tsconfig*.json",
    ]),
    visibility = ["//..."],
)
